package systemnotas.SystemNotasVisual;
import javax.swing.*;
import java.awt.*;

import systemnotas.Main;
import systemnotas.Persona;
import systemnotas.SistemaNotas;
/**
 *
 * @author 57322
 */
public class VentanaLogin extends javax.swing.JFrame {

    private SistemaNotas sistema;

    public VentanaLogin(SistemaNotas sistema) {
        this.sistema = sistema;

        // --- Configuración de la Ventana ---
        setTitle("Login - Sistema Académico");
        setSize(350, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null); // Centrar en la pantalla

        // --- Creación de Componentes ---
        JPanel panel = new JPanel(new GridLayout(3, 2, 10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15)); // Añadir margen

        JTextField campoUser = new JTextField();
        JPasswordField campoPass = new JPasswordField();
        JButton btnLogin = new JButton("Iniciar Sesión");
        
        // --- Añadir Componentes al Panel ---
        panel.add(new JLabel("Username:"));
        panel.add(campoUser);
        panel.add(new JLabel("Password:"));
        panel.add(campoPass);
        panel.add(new JLabel()); // Espacio en blanco para alinear el botón
        panel.add(btnLogin);
        
        // Añadir el panel principal a la ventana
        add(panel);

        // --- Lógica del Botón "Iniciar Sesión" ---
        btnLogin.addActionListener(e -> {
            String user = campoUser.getText().trim();
            String pass = new String(campoPass.getPassword());

            // 1. Llama al sistema para verificar las credenciales
            Persona personaLogueada = sistema.login(user, pass);

            // 2. Si las credenciales son correctas...
            if (personaLogueada != null) {
            // 3. Llama al controlador 'Main' para que abra la ventana de rol apropiada
            Main.iniciarSesion(personaLogueada, sistema);
                
                // 4. Cierra esta ventana de login
                this.dispose(); 
            } else {
                // 5. Si las credenciales son incorrectas, muestra un mensaje de error
                JOptionPane.showMessageDialog(this, "Credenciales incorrectas.", "Error de Login", JOptionPane.ERROR_MESSAGE);
            }
            });
        }

    

    /**
     * Creates new form VentanaLogin
     */
    public VentanaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
