/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package systemnotas.SystemNotasVisual;

import java.awt.*;
import javax.swing.*;
import systemnotas.Estudiante;
import systemnotas.Main;
import systemnotas.SistemaNotas;

/**
 *
 * @author 57322
 */
public class VentanaEstudiante extends javax.swing.JFrame {

        
    private final SistemaNotas sistema;
    private final Estudiante estudiante;

    public VentanaEstudiante(Estudiante estudiante, SistemaNotas sistema) {
        this.estudiante = estudiante;
        this.sistema = sistema;
        setTitle("Portal del Estudiante - " + estudiante.getNombre());
        setSize(500, 400);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout(10, 10));

        // --- Panel Superior con Botones ---
        JPanel panelSuperior = new JPanel(new FlowLayout(FlowLayout.CENTER));
        JButton btnVerReporte = new JButton("Ver Mi Reporte Académico");
        panelSuperior.add(btnVerReporte);

        // --- Área de Texto para el Reporte ---
        JTextArea areaReporte = new JTextArea();
        areaReporte.setEditable(false);
        areaReporte.setFont(new Font("Monospaced", Font.PLAIN, 12));
        JScrollPane scrollPane = new JScrollPane(areaReporte);
        scrollPane.setBorder(BorderFactory.createTitledBorder("Reporte de Notas"));

        // --- Panel Inferior para Cerrar Sesión ---
        JPanel panelInferior = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        JButton btnCerrarSesion = new JButton("Cerrar Sesión");
        panelInferior.add(btnCerrarSesion);

        add(panelSuperior, BorderLayout.NORTH);
        add(scrollPane, BorderLayout.CENTER);
        add(panelInferior, BorderLayout.SOUTH);

        // --- Lógica de Botones ---
        btnCerrarSesion.addActionListener(e -> {
            this.dispose();
            Main.mostrarVentanaLogin();
        });
        
        btnVerReporte.addActionListener(e -> {
            String reporte = generarReporteEstudiante();
            areaReporte.setText(reporte);
        });
        
        // Cargar el reporte automáticamente al abrir la ventana
        btnVerReporte.doClick();
    }
    
    private String generarReporteEstudiante() {
        StringBuilder reporte = new StringBuilder("--- Reporte Académico ---\n");
        reporte.append("Estudiante: ").append(estudiante.getNombre()).append("\n");
        reporte.append("Username: ").append(estudiante.getNickname()).append("\n\n");
        
        boolean encontrado = false;
        for (systemnotas.Inscripcion inscripcion : sistema.inscripciones) {
            if (inscripcion.getEstudiante().equals(estudiante)) {
                encontrado = true;
                reporte.append("Materia: ").append(inscripcion.getMateria().getNombre()).append("\n");
                reporte.append("  - Nota 1: ").append(inscripcion.getN1()).append("\n");
                reporte.append("  - Nota 2: ").append(inscripcion.getN2()).append("\n");
                reporte.append("  - Nota 3: ").append(inscripcion.getN3()).append("\n");
                reporte.append("  - Parcial: ").append(inscripcion.getParcial()).append("\n");
                reporte.append("  - Nota Final: ").append(String.format("%.2f", inscripcion.calcularFinal())).append("\n\n");
            }
        }
        
        if (!encontrado) {
            reporte.append("No tienes materias inscritas o calificaciones registradas.");
        }
        
        return reporte.toString();
    }

    public VentanaEstudiante() {
        this.estudiante = null;
        this.sistema = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
